<?php
/**
 * @var App\Blocks\HeaderBlock $this
 * @var App\Models\SessionModel $isLogged
 */
?>
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/styles/general/general.css">
    <title>Needful things</title>
</head>
<body>

<header class="header">

    <a href="../mainpage">
        <img class="header__logo" src="icons/Needful-things.svg" alt="logo">
    </a>
    <ul class="menu">

        <li class="menu__item <?php if ($this->underlined == 1) { ?>
            <?= 'menu__item_focus' ?>
        <?php  } ?>
        ">
            <a href="../mainpage" class="link">
                Mainpage
            </a>
        </li>
        <li class="menu__item <?php if ($this->underlined == 2) { ?>
            <?= 'menu__item_focus' ?>
        <?php  } ?>
        ">
            <a href="../product" class="link">
                Products
            </a>
        </li>
        <li class="menu__item <?php if ($this->underlined == 3) { ?>
            <?= 'menu__item_focus' ?>
        <?php  } ?>
        ">
            <a href="../storage" class="link">
                Storage
            </a>
        </li>
        <li class="menu__item <?php if ($this->underlined == 4) { ?>
            <?= 'menu__item_focus' ?>
        <?php  } ?>
        ">
            <a href="../category" class="link">
                Category
            </a>
        </li>
    </ul>

    <?php if (!$this->getCurrentId()) { ?>
    <div class="header__right-bar">
        <a href="addClient" class="sign-up link">sign up</a>
        <a href="login" class="button link link_white">
            sign in
        </a>
    </div>
    <?php } else { ?>
        <div class="header__right-bar">
            <a href="logOut" class="sign-up link">sign out</a>
            <a href="profile" class="button link link_white">
                profile
            </a>
        </div>
    <?php } ?>

</header>