<?php
/**
 * @var App\Blocks\FooterBlock $footer
 * @var App\Blocks\HeaderBlock $header
 * @var App\Blocks\Block $this
 */
?>
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="styles/general/general.css">
    <title>Needful things</title>
</head>
<body>

    <?php $header->render(); ?>

    <?php require_once ($this->buildTemplate()); ?>

    <?php $footer->render(); ?>

</body>
</html>
