<?php
/**
 * @var App\Models\Entity\CategoryModel $category
 * @var App\Blocks\CategoryBlock $this
 */
?>
<div class="main-space">
        <div class="welcome-card">
            <div class="element-box">
                <?php foreach ($this->getModel() as $category): ?>
                    <div class="element">
                <?= $this->sanitizeOutput($category->getCategory()) ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
</div>