<?php
/**
 * @var App\Models\Entity\CategoryModel $model
 * @var App\Blocks\CategoryBlock $this
 */
?>
<div class="main-space">
        <div class="welcome-card">
            <div class="element-box">
                <?php foreach ($this->getCategories() as $item): ?>
                    <div class="element">
                <?= $this->validateOutput($item['name']) ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
</div>