<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../styles/general/general.css">
    <title>Client</title>
</head>
<body>

<header class="header">

    <img class="header__logo" src="../icons/Needful-things.svg" alt="logo">
    <ul class="menu">

        <li class="menu__item">
            <a href="../mainpage" class="link">
                Mainpage
            </a>
        </li>
        <li class="menu__item">
            <a href="../product" class="link">
                Products
            </a>
        </li>
        <li class="menu__item">
            <a href="../storage" class="link">
                Storage
            </a>
        </li>
        <li class="menu__item">
            <a href="../category" class="link">
                Category
            </a>
        </li>
        <li class="menu__item menu__item_focus">
            <a href="../client" class="link">
                Client
            </a>
        </li>
    </ul>
    <a href="../order" class="order link link_white">
        Order
    </a>

</header>

    <div class="feed feed_row">
        <?php foreach ($this->getData() as $product): ?>
            <div class="welcome-card welcome-card_little">
                <div class="form">
                    <div class="photo-box photo-box_little">
                        <img class="photo photo_full" src="../img/background.jpg" alt="photo">
                    </div>
                </div>
                <div class="description">
                    <div class="description__item">
                        name: <?= $product['name'] ?>
                    </div>
                    <div class="description__item">
                        surname: <?= $product['surname'] ?>
                    </div>
                    <div class="description__item">
                        email: <?= $product['email'] ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

<?php require_once "constituents/footer.phtml" ?>

</body>
</html>