<?php
/**
 * @var App\Models\ClientModel $model
 */
?>
<div class="create-user">
    <a href="../addClient" class="button button__alternate link">
        create client
    </a>
</div>

<div class="main-space main-space_row">
    <?php $data = $model->getData() ?>
    <?php foreach ($data as $client): ?>
        <div class="welcome-card welcome-card_little">
            <a href="../editProfile?id=<?= $client['id'] ?>" class="edit">
                <img src="../icons/edit-button.svg" alt="edit" class="edit__svg">
            </a>
            <div class="form">
                <div class="photo-box photo-box_little">
                    <img class="photo photo_full" src="../img/background.jpg" alt="photo">
                </div>
            </div>
            <div class="description">
                <div class="description__item">
                    name: <?= $client['name'] ?>
                </div>
                <div class="description__item">
                    surname: <?= $client['surname'] ?>
                </div>
                <div class="description__item">
                    email: <?= $client['email'] ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
