<?php
/**
 * @var App\Blocks\ClientBlock $this
 * @var App\Models\ClientsModel $model
 */
?>
<div class="create-user">
    <a href="../addClient" class="button button__alternate link">
        create client
    </a>
</div>

<div class="main-space main-space_row">
    <?php foreach ($model->getData() as $client): ?>
        <div class="welcome-card welcome-card_little">
            <a href="../editProfile?id=<?= $client->getId() ?>" class="edit">
                <img src="../icons/edit-button.svg" alt="edit" class="edit__svg">
            </a>
            <div class="form">
                <div class="photo-box photo-box_little">
                    <img class="photo photo_full" src="../img/background.jpg" alt="photo">
                </div>
            </div>
            <div class="description">
                <div class="description__item">
                    name: <?= $client->getName() ?>
                </div>
                <div class="description__item">
                    surname: <?= $client->getSurname() ?>
                </div>
                <div class="description__item">
                    email: <?= $client->getEmail() ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
