<?php
/**
 * @var App\Models\ProductModel $model
 * @var App\Models\Resource\CategoryResourceModel $category
 */
?>
<div class="main-space">
    <div class="welcome-card">
        <?php $product = $model->getData() ?>
        <div class="form">
            <div class="form__name">
                <?= $product['name'] ?>
            </div>
            <div class="photo-box">
                <img src="../img/addClientPhoto.jpg" alt="picture" class="photo photo_full">
            </div>
        </div>
        <div class="description">
            <div class="description__item">
                price: <?= $product['price'] ?> rub
            </div>
            <div class="description__item">
                country: <?= $product['country'] ?>
            </div>
            <div class="description__item">
                brand: <?= $product['brand'] ?>
            </div>
            <div class="description__item">
                date: <?= $product['date'] ?>
            </div>
            <?php $categories = $category->getAllCategories($product['id_product']); ?>
            <div class="description__item">
                category:
                <?= implode(' ', array_column($categories, 'name')); ?>
            </div>
        </div>
    </div>
</div>