<?php
/**
 * @var App\Blocks\Block $this
 */
?>
<div class="main-space">
    <div class="welcome-card input-form">
        <div class="form">
            <?php $id = $this->getCurrentClient(); ?>
            <div class="form__name">
                Change information
            </div>
            <div class="photo-box">
                <img class="photo photo_full" src="../img/addClientPhoto.jpg" alt="beauty">
            </div>
        </div>
        <form class="registration"  action="" method="post">
            <div class="registration__field">
                <input
                    class="registration__input"
                    type="text"
                    name="name"
                    placeholder="name"
                    value="<?= $this->validateOutput($id['name']) ?>"
                >
            </div>

            <input name="csrf_token" type="hidden" value="<?= $this->getCsrfToken() ?>">

            <div class="registration__field">
                <input
                    class="registration__input"
                    type="text"
                    name="surname"
                    placeholder="surname"
                    value="<?= $this->validateOutput($id['surname']) ?>"
                >
            </div>

            <div class="registration__field">
                <input
                    class="registration__input"
                    type="email"
                    name="email"
                    placeholder="email"
                    value="<?= $this->validateOutput($id['email']) ?>"
                >
            </div>

            <div class="registration__field">
                <input class="registration__input" type="password" name="password" placeholder="password">
            </div>

            <div class="registration__field">
                <input
                    class="registration__input"
                    type="password"
                    name="re-password"
                    placeholder="repeat password"
                >
            </div>

            <div class="registration__field">
                <input class="registration__submit" type="submit" name="submit" value="add">
            </div>
        </form>
    </div>
</div>