<div class="main-space">
    <div class="login">
        <div class="form">
            <div class="form__name">
                Sign In
            </div>
        <form class="registration"  action="" method="post">
            <div class="registration__field">
                <input class="login__row" type="email" name="email" placeholder="email">
            </div>

            <div class="registration__field">
                <input class="login__row" type="text" name="password" placeholder="password">
            </div>

            <div class="registration__field">
                <input class="login__submit" type="submit" name="submit" value="sign in">
            </div>
        </form>
    </div>
</div>