<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../styles/general/general.css">
    <title>Mainpage</title>
</head>
<body>

<header class="header">

    <img class="header__logo" src="../icons/Needful-things.svg" alt="logo">
    <ul class="menu">

        <li class="menu__item menu__item_focus">
            <a href="../mainpage" class="link">
                Mainpage
            </a>
        </li>
        <li class="menu__item">
            <a href="../product" class="link">
                Products
            </a>
        </li>
        <li class="menu__item">
            <a href="../storage" class="link">
                Storage
            </a>
        </li>
        <li class="menu__item">
            <a href="../category" class="link">
                Category
            </a>
        </li>
        <li class="menu__item">
            <a href="../client" class="link">
                Client
            </a>
        </li>
    </ul>
    <a href="../order" class="order link link_white">
        Order
    </a>

</header>

<div class="greet-card">
     Welcome to needful things, stranger. <br>
    There you can find everything you need, enjoy
</div>

<?php require_once "constituents/footer.phtml" ?>

</body>
</html>