<?php
/**
 * @var App\Blocks\OrderBlock $this
 */
?>
<div class="main-space">
    <div class="check-box">
        <h2 class="check-box__title">
            Purchase price
        </h2>
        <div class="bottom-bar">
        <?php $total = 0; ?>
        <?php foreach ($this->getOrder() as $item): ?>
            <div class="check-box__unit">
                <div class="product">
                    <?= $this->validateOutput($item['name']) ?>
                </div>
                <div class="check__item">
                    <?= $this->validateOutput($item['total']) ?>
                    <?php $total += $item['total'] ?>
                </div>
            </div>
        <?php endforeach; ?>
            <div class="total">
                <div class="total__name">
                    Total:
                </div>
                <div class="total__cash">
                    <?= $total ?>
                </div>
            </div>
        </div>
    </div>
</div>
