<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../styles/general/general.css">
    <title>Order</title>
</head>
<body>

<header class="header">

    <img class="header__logo" src="../icons/Needful-things.svg" alt="logo">
    <ul class="menu">

        <li class="menu__item">
            <a href="../mainpage" class="link">
                Mainpage
            </a>
        </li>
        <li class="menu__item">
            <a href="../product" class="link">
                Products
            </a>
        </li>
        <li class="menu__item">
            <a href="../storage" class="link">
                Storage
            </a>
        </li>
        <li class="menu__item">
            <a href="../category" class="link">
                Category
            </a>
        </li>
        <li class="menu__item">
            <a href="../client" class="link">
                Client
            </a>
        </li>
    </ul>
    <a href="../order" class="order link link_white">
        Order
    </a>

</header>

<div class="feed">
    <div class="check-box">
        <h2 class="check-box__title">
            Purchase price
        </h2>
        <div class="bottom-bar">
        <?php $total = 0; ?>
        <?php foreach ($this->getData() as $item): ?>
            <div class="check-box__unit">
                <div class="product">
                    Наименование товара
                </div>
                <div class="check__item">
                    <?= $item ?>
                    <?php $total += $item ?>
                </div>
            </div>
        <?php endforeach; ?>
            <div class="total">
                <div class="total__name">
                    Total:
                </div>
                <div class="total__cash">
                    <?= $total ?>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require_once "constituents/footer.phtml" ?>

</body>
</html>