<?php
/**
 * @var App\Models\Entity\ProductModel $model
 * @var App\Models\Resource\CategoryResourceModel $category
 */
?>
<div class="main-space">
    <?php $product = $model->getData() ?>
    <div class="welcome-card">
        <div class="delete">
            <a href="../deleteEntity?id=<?= $this->ValidateOutput($product['id_product']) ?>" class="delete__block">
                <img class="delete__icon" src="../icons/x.png" alt="x">
            </a>
        </div>
        <div class="form">
            <div class="form__name">
                <?= $this->ValidateOutput($product['name']) ?>
            </div>
            <div class="photo-box">
                <img src="../img/addClientPhoto.jpg" alt="picture" class="photo photo_full">
            </div>
        </div>
        <div class="description">
            <div class="description__item">
                price: <?= $this->ValidateOutput($product['price']) ?> rub
            </div>
            <div class="description__item">
                country: <?= $this->ValidateOutput($product['country']) ?>
            </div>
            <div class="description__item">
                brand: <?= $this->ValidateOutput($product['brand']) ?>
            </div>
            <div class="description__item">
                date: <?= $this->ValidateOutput($product['date']) ?>
            </div>
            <?php $categories = $category->getAllCategories($product['id_product']); ?>
            <div class="description__item">
                category:
                <?= $this->ValidateOutput(implode(' ', (array_column($categories, 'name')))); ?>
            </div>
        </div>
    </div>
</div>