<?php
/**
 * @var App\Blocks\Block $this
 * @var App\Models\Entity\ProductModel $product
 */
?>
<div class="main-space">
    <?php $product = $this->getModel()[0] ?>
    <div class="welcome-card">
        <div class="delete">
            <a href="../deleteEntity?id=<?= $this->sanitizeOutput($product->getId()) ?>" class="delete__block">
                <img class="delete__icon" src="../icons/x.png" alt="x">
            </a>
        </div>
        <div class="form">
            <div class="form__name">
                <?= $this->sanitizeOutput($product->getName()) ?>
            </div>
            <div class="photo-box">
                <img src="../img/addClientPhoto.jpg" alt="picture" class="photo photo_full">
            </div>
        </div>
        <div class="description">
            <div class="description__item">
                price: <?= $this->sanitizeOutput($product->getPrice()) ?> rub
            </div>
            <div class="description__item">
                country: <?= $this->sanitizeOutput($product->getCountry()) ?>
            </div>
            <div class="description__item">
                brand: <?= $this->sanitizeOutput($product->getBrand()) ?>
            </div>
            <div class="description__item">
                date: <?= $this->sanitizeOutput($product->getDate()) ?>
            </div>
            <div class="description__item">
                category:
                <?= $this->sanitizeOutput($this->getProductCategoriesText($product->getId())); ?>
            </div>
        </div>
    </div>
</div>