<?php
/**
 * @var App\Models\Resource\CategoryResourceModel $category
 * @var App\Blocks\ProductBlock $this
 */
?>
<div class="main-space">
    <?php foreach ($this->getData() as $product): ?>
    <div class="welcome-card">
        <div class="form">
            <a href="../productUnit?id=<?= $product['id_product'] ?>"
               class="form__name link name"
               data-replace="<?= $product['name'] ?>">
                <span class="name__item">
                    <?= $product['name'] ?>
                </span>
            </a>
            <div class="photo-box">
                <img class="photo" src="../img/background.jpg" alt="photo">
            </div>
        </div>
        <div class="description description_tabbed">
            <div class="description__item">
                price: <?= $product['price'] ?> rub
            </div>
            <div class="description__item">
                country: <?= $product['country'] ?>
            </div>
            <div class="description__item">
                brand: <?= $product['brand'] ?>
            </div>
            <div class="description__item">
                date: <?= $product['date'] ?>
            </div>
                <?php $categories = $category->getAllCategories($product['id_product']); ?>
            <div class="description__item">
                category:
                <?= implode(' ', array_column($categories, 'name')); ?>
            </div>
        </div>
    </div>
        <?php endforeach; ?>
</div>
