<?php
/**
 * @var App\Blocks\Block $this
 * @var App\Models\Entity\ProductModel $product
 */
?>
<div class="main-space">
    <?php $product = $this->getProduct() ?>
    <div class="welcome-card">
        <div class="interact">
            <div class="delete">
                <a href="../deleteEntity?id=<?= $product->getId() ?>" class="delete delete_shifted">
                    <img class="delete__icon" src="icons/x.png" alt="x">
                </a>
            </div>
            <div class="delete">
                <a href="../editProduct?id=<?= $product->getId() ?>" class="edit edit_shifted">
                    <img src="icons/edit-button.svg" alt="edit" class="edit__svg ">
                </a>
            </div>
        </div>
        <div class="form">
            <div class="form__name">
                <?= $this->sanitizeOutput($product->getName()) ?>
            </div>
            <div class="photo-box">
                <img src="img/addClientPhoto.jpg" alt="picture" class="photo photo_full">
            </div>
        </div>
        <div class="description">
            <div class="description__item">
                price: <?= $this->sanitizeOutput($product->getPrice()) ?> rub
            </div>
            <div class="description__item">
                country: <?= $this->sanitizeOutput($product->getCountry()) ?>
            </div>
            <div class="description__item">
                brand: <?= $this->sanitizeOutput($product->getBrand()) ?>
            </div>
            <div class="description__item">
                date: <?= $this->sanitizeOutput($product->getDate()) ?>
            </div>
            <div class="description__item">
                category:
                <?= $this->sanitizeOutput($this->getProductCategoriesText($product->getId())); ?>
            </div>
        </div>
    </div>
</div>