<?php
/**
 * @var App\Blocks\ProductBlock $this
 * @var App\Models\Entity\ProductModel $product
 */
?>
<div class="main-space">

    <div class="create">
        <a href="../addProduct" class="button button__alternate link">
            add product
        </a>
    </div>
    <?php foreach ($this->getData() as $product): ?>
    <div class="welcome-card">
        <div class="interact">
            <div class="delete">
                <a href="../deleteEntity?id=<?= $product->getId() ?>" class="delete delete_shifted">
                    <img class="delete__icon" src="icons/x.png" alt="x">
                </a>
            </div>
            <div class="delete">
                <a href="../editProduct?id=<?= $product->getId() ?>" class="edit edit_shifted">
                    <img src="icons/edit-button.svg" alt="edit" class="edit__svg ">
                </a>
            </div>
        </div>
        <div class="form">
            <a href="../productUnit?id=<?= $product->getId() ?>"
               class="form__name link name"
               data-replace="<?= $this->sanitizeOutput($product->getName()) ?>">
                <span class="name__item">
                    <?= $this->sanitizeOutput($product->getName()) ?>
                </span>
            </a>
            <div class="photo-box">
                <img class="photo" src="img/background.jpg" alt="photo">
            </div>
        </div>
        <div class="description description_tabbed">
            <div class="description__item">
                price: <?= $this->sanitizeOutput($product->getPrice()) ?> rub
            </div>
            <div class="description__item">
                country: <?= $this->sanitizeOutput($product->getCountry()) ?>
            </div>
            <div class="description__item">
                brand: <?= $this->sanitizeOutput($product->getBrand()) ?>
            </div>
            <div class="description__item">
                date: <?= $this->sanitizeOutput($product->getDate()) ?>
            </div>
            <div class="description__item">
                category:
                <?= $this->sanitizeOutput($this->getProductCategoriesText($product->getId())); ?>
            </div>
        </div>
    </div>
        <?php endforeach; ?>
</div>
