<?php
/**
 * @var App\Blocks\Block $this
 * @var App\Models\Entity\ClientModel $client
 */
?>

<div class="main-space">
    <?php $client = $this->getCurrentClient() ?>
    <div class="profile">
        <a href="../editProfile?id=<?= $this->sanitizeOutput($client->getId()) ?>" class="edit">
            <img src="../icons/edit-button.svg" alt="edit" class="edit__svg">
        </a>
        <div class="form">
            <div class="photo-box photo-box_little">
                <img class="photo photo_full" src="../img/background.jpg" alt="photo">
            </div>
        </div>
        <div class="description">
            <div class="description__item">
                name: <?= $this->sanitizeOutput($client->getName()) ?>
            </div>
            <div class="description__item">
                surname: <?= $this->sanitizeOutput($client->getSurname()) ?>
            </div>
            <div class="description__item">
                email: <?= $this->sanitizeOutput($client->getEmail()) ?>
            </div>
        </div>
    </div>
        <a href="/order" class="order link">
            check my orders
        </a>
</div>
