<?php
/**
 * @var App\Models\StorageModel $model
 */
?>
<div class="main-space">
    <div class="welcome-card">
        <div class="element-box">
            <?php foreach ($model->getData() as $item): ?>
                <div class="element element_large">
                    <?= $item['address'] ?>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="photo-box photo">
            <img class="photo photo_full" src="../img/map.webp" alt="">
        </div>
    </div>
</div>
