<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../../styles/general/general.css">
    <title>Needful things</title>
</head>
<body>

<header class="header">

    <a href="../mainpage">
        <img class="header__logo" src="../../icons/Needful-things.svg" alt="logo">
    </a>
    <ul class="menu">

        <li class="menu__item <?php if ($this->focused == 1) { ?>
            <?= 'menu__item_focus' ?>
        <?php  } ?>
        ">
            <a href="../mainpage" class="link">
                Mainpage
            </a>
        </li>
        <li class="menu__item <?php if ($this->focused == 2) { ?>
            <?= 'menu__item_focus' ?>
        <?php  } ?>
        ">
            <a href="../product" class="link">
                Products
            </a>
        </li>
        <li class="menu__item <?php if ($this->focused == 3) { ?>
            <?= 'menu__item_focus' ?>
        <?php  } ?>
        ">
            <a href="../storage" class="link">
                Storage
            </a>
        </li>
        <li class="menu__item <?php if ($this->focused == 4) { ?>
            <?= 'menu__item_focus' ?>
        <?php  } ?>
        ">
            <a href="../category" class="link">
                Category
            </a>
        </li>
        <li class="menu__item <?php if ($this->focused == 5) { ?>
            <?= 'menu__item_focus' ?>
        <?php  } ?>
        ">
            <a href="../client" class="link">
                Client
            </a>
        </li>
    </ul>

    <a href="../order" class="order link link_white">
        Order
    </a>

</header>